In [ ]:
import sys

print("Ejecutable:", sys.executable)
print("Versión:", sys.version)

In [1]:
import torch
print(torch.__version__)

2.14.1+cu130

In [2]:
from transformers import pipeline

print("Transformers pipeline OK")

/home/codespace/.local/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Transformers pipeline OK

In [ ]:
%pip install transformers

In [3]:
modelo_1 = pipeline(
    "sentiment-analysis",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
)

Loading weights: 100%|██████████| 104/104 [00:01<00:00, 82.77it/s]

In [ ]:
%pip install torch

In [ ]:
modelo_1("This movie was absolutely amazing!")

## Primera prueba del Modelo 1

Utilizamos el modelo `distilbert/distilbert-base-uncased-finetuned-sst-2-english`
mediante `pipeline` de Transformers.

La frase utilizada fue:

> "This movie was absolutely amazing!"

El modelo devuelve una etiqueta de sentimiento (`POSITIVE` o `NEGATIVE`)
junto con un valor de confianza (`score`).

In [5]:
modelo_1 = pipeline(
    "sentiment-analysis",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
)

resultado = modelo_1("This movie was absolutely amazing!")
print(resultado)

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 7156.58it/s]

[{'label': 'POSITIVE', 'score': 0.9998781681060791}]

In [ ]:
frases = [
    "This movie was absolutely amazing!",
    "I hated every minute of this movie.",
    "La película fue excelente y me encantó.",
    "La película fue aburrida y demasiado larga.",
    "Yeah, great movie... I almost fell asleep.",
    "This movie was sick!",
    "Meh.",
    "The acting was good, but the story was terrible."
]

In [10]:
resultados_modelo_1 = modelo_1(frases)

resultados_modelo_1

[{'label': 'POSITIVE', 'score': 0.9998781681060791},
 {'label': 'NEGATIVE', 'score': 0.9996154308319092},
 {'label': 'POSITIVE', 'score': 0.9832308292388916},
 {'label': 'NEGATIVE', 'score': 0.9936158657073975},
 {'label': 'NEGATIVE', 'score': 0.9850236177444458},
 {'label': 'NEGATIVE', 'score': 0.9997525811195374},
 {'label': 'NEGATIVE', 'score': 0.5079557299613953},
 {'label': 'NEGATIVE', 'score': 0.9929336309432983}]

In [ ]:
modelo_2 = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

In [ ]:
%pip install tiktoken

In [ ]:
%pip install sentencepiece

In [ ]:
import sentencepiece

print(sentencepiece.__version__)

In [ ]:
from transformers import AutoTokenizer

tokenizer_2 = AutoTokenizer.from_pretrained(
    "cardiffnlp/twitter-xlm-roberta-base-sentiment",
    use_fast=False
)

In [ ]:
import transformers

print(transformers.__version__)

In [ ]:
pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment",
    tokenizer="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)



modelo_2 = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment",
    tokenizer="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

In [6]:
modelo_2 = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment-multilingual"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 4645.01it/s]

In [11]:
resultados_modelo_2 = modelo_2(frases)

resultados_modelo_2

[{'label': 'positive', 'score': 0.9855308532714844},
 {'label': 'negative', 'score': 0.9136499166488647},
 {'label': 'positive', 'score': 0.9853597283363342},
 {'label': 'negative', 'score': 0.9610550999641418},
 {'label': 'positive', 'score': 0.9855705499649048},
 {'label': 'negative', 'score': 0.8911973237991333},
 {'label': 'neutral', 'score': 0.612568199634552},
 {'label': 'negative', 'score': 0.8974964022636414}]

In [8]:
frases = [
    "This movie was absolutely amazing!",
    "I hated every minute of this movie.",
    "La película fue excelente y me encantó.",
    "La película fue aburrida y demasiado larga.",
    "Yeah, great movie... I almost fell asleep.",
    "This movie was sick!",
    "Meh.",
    "The acting was good, but the story was terrible."
]

In [12]:
import pandas as pd

esperados = [
    "positive",
    "negative",
    "positive",
    "negative",
    "negative",
    "positive",
    "neutral",
    "negative"
]

tabla_comparacion = pd.DataFrame({
    "Frase": frases,
    "Esperado": esperados,
    "Modelo 1": [r["label"].lower() for r in resultados_modelo_1],
    "Score M1": [r["score"] for r in resultados_modelo_1],
    "Modelo 2": [r["label"].lower() for r in resultados_modelo_2],
    "Score M2": [r["score"] for r in resultados_modelo_2]
})

tabla_comparacion

,Frase,Esperado,Modelo 1,Score M1,Modelo 2,Score M2
0,This movie was absolutely amazing!,positive,positive,0.999878,positive,0.985531
1,I hated every minute of this movie.,negative,negative,0.999615,negative,0.913650
2,La película fue excelente y me encantó.,positive,positive,0.983231,positive,0.985360
3,La película fue aburrida y demasiado larga.,negative,negative,0.993616,negative,0.961055
4,"Yeah, great movie... I almost fell asleep.",negative,negative,0.985024,positive,0.985571
5,This movie was sick!,positive,negative,0.999753,negative,0.891197
6,Meh.,neutral,negative,0.507956,neutral,0.612568
7,"The acting was good, but the story was terrible.",negative,negative,0.992934,negative,0.897496

In [ ]:
print("Frases:", len(frases))
print("Esperados:", len(esperados))
print("Modelo 1:", len(resultados_modelo_1))
print("Modelo 2:", len(resultados_modelo_2))

In [ ]:
esperados = [
    "positive",
    "negative",
    "positive",
    "negative",
    "negative",
    "positive",
    "neutral",
    "negative"
]

In [ ]:
print("Frases:", len(frases))
print("Esperados:", len(esperados))
print("Modelo 1:", len(resultados_modelo_1))
print("Modelo 2:", len(resultados_modelo_2))

In [ ]:
tabla_comparacion = pd.DataFrame({
    "Frase": frases,
    "Esperado": esperados,
    "Modelo 1": [r["label"].lower() for r in resultados_modelo_1],
    "Score M1": [r["score"] for r in resultados_modelo_1],
    "Modelo 2": [r["label"].lower() for r in resultados_modelo_2],
    "Score M2": [r["score"] for r in resultados_modelo_2]
})

tabla_comparacion

In [ ]:
tabla_comparacion["Acierto M1"] = (
    tabla_comparacion["Modelo 1"] == tabla_comparacion["Esperado"]
)

tabla_comparacion["Acierto M2"] = (
    tabla_comparacion["Modelo 2"] == tabla_comparacion["Esperado"]
)

tabla_comparacion

In [ ]:
print("Aciertos Modelo 1:", tabla_comparacion["Acierto M1"].sum(), "de", len(tabla_comparacion))
print("Aciertos Modelo 2:", tabla_comparacion["Acierto M2"].sum(), "de", len(tabla_comparacion))

In [ ]:
tabla_comparacion[
    (tabla_comparacion["Acierto M1"] == False) |
    (tabla_comparacion["Acierto M2"] == False)
]

In [ ]:
import huggingface_hub

print(huggingface_hub.__version__)

In [ ]:
import os

print("Token configurado:", os.getenv("HF_TOKEN") is not None)

In [ ]:
import os

print("Token configurado:", os.getenv("HF_TOKEN") is not None)

In [ ]:
from huggingface_hub import InferenceClient

cliente = InferenceClient()

print("InferenceClient configurado correctamente")

In [ ]:
resultado_api_1 = cliente.text_classification(
    "This movie was absolutely amazing!",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
)

resultado_api_1

In [ ]:
import os

token = os.getenv("HF_TOKEN")

print("Existe:", token is not None)
print("Tiene contenido:", bool(token))
print("Empieza con hf_:", token.startswith("hf_") if token else False)
print("Longitud:", len(token) if token else 0)

In [ ]:
from huggingface_hub import HfApi

api = HfApi(token=os.getenv("HF_TOKEN"))

usuario_hf = api.whoami()

print("Token válido.")
print("Usuario:", usuario_hf["name"])

In [ ]:
import os

token = os.getenv("HF_TOKEN")

print("Existe:", token is not None)
print("Tiene contenido:", bool(token))
print("Empieza con hf_:", token.startswith("hf_") if token else False)
print("Longitud:", len(token) if token else 0)

In [ ]:
import os

In [ ]:
print("Longitud:", len(os.environ["HF_TOKEN"]))

In [ ]:
from huggingface_hub import HfApi

api = HfApi(token=os.environ["HF_TOKEN"])
usuario_hf = api.whoami()

print("Token válido.")
print("Usuario:", usuario_hf["name"])

In [ ]:
from huggingface_hub import InferenceClient
import os

cliente = InferenceClient(token=os.environ["HF_TOKEN"])

print("InferenceClient configurado correctamente")

In [ ]:
resultado_api_1 = cliente.text_classification(
    "This movie was absolutely amazing!",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
)

resultado_api_1

In [ ]:
print(cliente.provider)

In [ ]:
import time

inicio = time.time()

resultado_pipeline = modelo_1(
    "This movie was absolutely amazing!"
)

fin = time.time()

print("Resultado:", resultado_pipeline)
print("Tiempo:", round(fin - inicio, 4), "segundos")

In [ ]:
from transformers import pipeline

modelo_1 = pipeline(
    "sentiment-analysis",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
)

print("Modelo 1 cargado correctamente")

In [ ]:
import time

inicio = time.time()

resultado_pipeline_2 = modelo_1(
    "This movie was absolutely amazing!"
)

fin = time.time()

print("Resultado:", resultado_pipeline_2)
print("Tiempo segunda predicción:", round(fin - inicio, 4), "segundos")

In [ ]:
print("Tipo del resultado:")
print(type(resultado_pipeline_2))

print("\nPrimer resultado:")
print(resultado_pipeline_2[0])

print("\nTipo del primer resultado:")
print(type(resultado_pipeline_2[0]))

In [ ]:
resultado = resultado_pipeline_2[0]

print("Label:", resultado["label"])
print("Score:", resultado["score"])

### Error con InferenceClient: 402 Payment Required

Al intentar utilizar `InferenceClient` con el modelo `distilbert/distilbert-base-uncased-finetuned-sst-2-english`, la solicitud devolvió un error HTTP 402 (`Payment Required`).

El token de Hugging Face fue validado correctamente, por lo que el problema no estaba relacionado con la autenticación. El mensaje de la API indicó que la cuenta no tenía créditos disponibles para utilizar Inference Providers.

Como alternativa, se continuó utilizando `pipeline`, que permite ejecutar el modelo localmente en el entorno de trabajo sin realizar una llamada remota al proveedor de inferencia.

In [2]:
resultado = modelo("This movie was fantastic!")
print(resultado)

NameError: name 'modelo' is not defined

In [ ]:
resultado_modelo_2 = modelo_2("This movie was absolutely amazing!")
print(resultado_modelo_2)

[{'label': 'positive', 'score': 0.9855308532714844}]

In [ ]:
print("Cantidad de frases:", len(frases))
print(frases)

Cantidad de frases: 8
['This movie was absolutely amazing!', 'I hated every minute of this movie.', 'La película fue excelente y me encantó.', 'La película fue aburrida y demasiado larga.', 'Yeah, great movie... I almost fell asleep.', 'This movie was sick!', 'Meh.', 'The acting was good, but the story was terrible.']

In [ ]:
print("Aciertos Modelo 1:", tabla_comparacion["Acierto M1"].sum(), "/ 8")
print("Porcentaje Modelo 1:", tabla_comparacion["Acierto M1"].mean() * 100, "%")

print("Aciertos Modelo 2:", tabla_comparacion["Acierto M2"].sum(), "/ 8")
print("Porcentaje Modelo 2:", tabla_comparacion["Acierto M2"].mean() * 100, "%")

Aciertos Modelo 1: 6 / 8
Porcentaje Modelo 1: 75.0 %
Aciertos Modelo 2: 6 / 8
Porcentaje Modelo 2: 75.0 %

In [ ]:
tabla_comparacion["Acierto M1"] = (
    tabla_comparacion["Esperado"] == tabla_comparacion["Modelo 1"]
)

tabla_comparacion["Acierto M2"] = (
    tabla_comparacion["Esperado"] == tabla_comparacion["Modelo 2"]
)

tabla_comparacion

,Frase,Esperado,Modelo 1,Score M1,Modelo 2,Score M2,Acierto M1,Acierto M2
0,This movie was absolutely amazing!,positive,positive,0.999878,positive,0.985531,True,True
1,I hated every minute of this movie.,negative,negative,0.999615,negative,0.913650,True,True
2,La película fue excelente y me encantó.,positive,positive,0.983231,positive,0.985360,True,True
3,La película fue aburrida y demasiado larga.,negative,negative,0.993616,negative,0.961055,True,True
4,"Yeah, great movie... I almost fell asleep.",negative,negative,0.985024,positive,0.985571,True,False
5,This movie was sick!,positive,negative,0.999753,negative,0.891197,False,False
6,Meh.,neutral,negative,0.507956,neutral,0.612568,False,True
7,"The acting was good, but the story was terrible.",negative,negative,0.992934,negative,0.897496,True,True

In [ ]:
import time

inicio = time.time()
resultados_tiempo = modelo_1(frases)
fin = time.time()

tiempo_total = fin - inicio

print("Tiempo total:", round(tiempo_total, 4), "segundos")
print("Cantidad de frases:", len(frases))
print("Tiempo promedio por frase:", round(tiempo_total / len(frases), 4), "segundos")

Tiempo total: 0.3697 segundos
Cantidad de frases: 8
Tiempo promedio por frase: 0.0462 segundos

In [ ]:
import time

inicio = time.time()
resultados_tiempo_2 = modelo_2(frases)
fin = time.time()

tiempo_total_2 = fin - inicio

print("Tiempo total:", round(tiempo_total_2, 4), "segundos")
print("Cantidad de frases:", len(frases))
print("Tiempo promedio por frase:", round(tiempo_total_2 / len(frases), 4), "segundos")

Tiempo total: 0.6581 segundos
Cantidad de frases: 8
Tiempo promedio por frase: 0.0823 segundos

In [ ]:
print("Tipo de modelo_1:", type(modelo_1))

resultado = modelo_1("This movie was amazing!")

print("Tipo de resultado:", type(resultado))
print("Tipo del primer elemento:", type(resultado[0]))
print("Resultado completo:", resultado)
print("Etiqueta:", resultado[0]["label"])
print("Confianza:", resultado[0]["score"])

Tipo de modelo_1: <class 'transformers.pipelines.text_classification.TextClassificationPipeline'>
Tipo de resultado: <class 'list'>
Tipo del primer elemento: <class 'dict'>
Resultado completo: [{'label': 'POSITIVE', 'score': 0.9998800754547119}]
Etiqueta: POSITIVE
Confianza: 0.9998800754547119

In [ ]:
from huggingface_hub import InferenceClient

print("InferenceClient importado correctamente")

InferenceClient importado correctamente

In [ ]:
import os
from huggingface_hub import InferenceClient

token = os.getenv("HF_TOKEN")

if not token:
    print("No se encontró HF_TOKEN en las variables de entorno.")
else:
    cliente = InferenceClient(
        model="distilbert/distilbert-base-uncased-finetuned-sst-2-english",
        token=token
    )
    print("Cliente configurado correctamente.")

No se encontró HF_TOKEN en las variables de entorno.

In [ ]:
import os

print("HF_TOKEN disponible:", bool(os.getenv("HF_TOKEN")))

HF_TOKEN disponible: False

In [ ]:
import os

print("HF_TOKEN disponible:", bool(os.getenv("HF_TOKEN")))

HF_TOKEN disponible: True

In [ ]:
import os
import time
from huggingface_hub import InferenceClient

cliente = InferenceClient(
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english",
    token=os.getenv("HF_TOKEN")
)

inicio = time.time()

try:
    resultado_remoto = cliente.text_classification(
        "This movie was absolutely amazing!"
    )

    fin = time.time()

    print("Resultado:", resultado_remoto)
    print("Tiempo:", round(fin - inicio, 4), "segundos")
    print("Tipo de resultado:", type(resultado_remoto))

except Exception as e:
    print("Error:", type(e).__name__)
    print("Detalle:", str(e))

Error: HfHubHTTPError
Detalle: Client error '402 Payment Required' for url 'https://router.huggingface.co/hf-inference/models/distilbert/distilbert-base-uncased-finetuned-sst-2-english' (Request ID: Root=1-6ad144f1-3c8aeacb5eb8af8b0b32bc2a;ed9ca44d-c84c-4c30-8692-ccc56b229e1a)
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402

You have no remaining credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get monthly included credits.

**Error 402 Payment Required — InferenceClient**

Al probar la inferencia remota con Hugging Face, inicialmente se produjo un error 403 Forbidden porque el token no tenía los permisos necesarios para utilizar Inference Providers. Se corrigieron los permisos y la autenticación pasó a funcionar.

Posteriormente, la solicitud devolvió un error 402 Payment Required, indicando que la cuenta no tenía créditos disponibles para realizar inferencias remotas. Por este motivo, no fue posible medir el tiempo de respuesta del servicio remoto.

La alternativa local funcionó correctamente y permitió comparar ambos modelos con las mismas ocho frases: los dos obtuvieron un 75 % de aciertos. DistilBERT tardó 0,3697 segundos y XLM-RoBERTa, 0,6581 segundos en procesar las ocho frases. Estas mediciones corresponden a ejecuciones locales con los modelos ya cargados.

### Conclusiones de la comparación de modelos

Probamos dos modelos de análisis de sentimientos con las mismas ocho frases. DistilBERT obtuvo 6 aciertos de 8 (75 %) y XLM-RoBERTa también obtuvo 6 aciertos de 8 (75 %).

En las mediciones locales, DistilBERT tardó 0,3697 segundos en procesar las ocho frases, con un promedio de 0,0462 segundos por frase. XLM-RoBERTa tardó 0,6581 segundos, con un promedio de 0,0823 segundos por frase.

En esta prueba, DistilBERT fue más rápido, aunque ambos obtuvieron el mismo porcentaje de aciertos. Los dos modelos tuvieron dificultades con expresiones informales o ambiguas, como «This movie was sick!». XLM-RoBERTa clasificó «Meh.» como neutral, mientras que DistilBERT la clasificó como negativa.

Estos resultados corresponden a un conjunto pequeño de ocho frases y no permiten afirmar que los modelos tengan una precisión general del 75 %.

También probamos InferenceClient para ejecutar el modelo en un servidor remoto de Hugging Face. La solicitud terminó con un error HTTP 402 porque no había créditos disponibles. Por ese motivo, no pudimos medir el tiempo de respuesta remoto ni compararlo directamente con la ejecución local.

Elegimos pipeline para la aplicación porque permitió ejecutar el modelo sin depender de créditos de inferencia remota.

### Análisis de una llamada al modelo

En la instrucción `modelo_1("This movie was amazing!")`, utilizamos el objeto `modelo_1`, que es una instancia de `TextClassificationPipeline`.

- **Objeto:** `modelo_1`.
- **Método de uso:** llamamos al objeto como una función para clasificar texto.
- **Argumento:** `"This movie was amazing!"`, que es la frase que queremos analizar.
- **Valor de retorno:** una lista (`list`) que contiene un diccionario (`dict`).
- **Atributos del resultado:** el diccionario contiene las claves `label` y `score`. La primera indica la etiqueta asignada y la segunda el puntaje de confianza del modelo.

Por ejemplo, `resultado[0]["label"]` permite acceder a la etiqueta de la primera predicción y `resultado[0]["score"]` permite consultar su

### Análisis de InferenceClient

`InferenceClient` permite enviar una solicitud a un proveedor remoto de inferencia de Hugging Face. A diferencia de `pipeline`, que ejecuta el modelo en el entorno local, esta alternativa necesita conectarse a un servicio externo.

En nuestro experimento, configuramos un cliente con el modelo `distilbert/distilbert-base-uncased-finetuned-sst-2-english` y utilizamos el método `text_classification()` para enviar una frase.

La solicitud no devolvió una predicción porque el servicio respondió con el error HTTP 402 Payment Required, indicando que no había créditos disponibles. Por lo tanto, no pudimos comprobar el tipo de retorno de una respuesta remota exitosa ni medir su tiempo de ejecución.

Este resultado también es parte del experimento: registramos el error real y evitamos inventar una respuesta o un tiempo de ejecución que no obtuvimos.

In [3]:
resultado_2 = modelo_2("La película fue excelente y me encantó.")

print("Tipo de resultado:", type(resultado_2))
print("Tipo del primer elemento:", type(resultado_2[0]))
print("Resultado completo:", resultado_2)
print("Etiqueta:", resultado_2[0]["label"])
print("Confianza:", resultado_2[0]["score"])

NameError: name 'modelo_2' is not defined

In [5]:
from transformers import pipeline

modelo_2 = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment-multilingual"
)

/home/codespace/.local/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 10294.34it/s]

In [6]:
resultado_2 = modelo_2("La película fue excelente y me encantó.")

print("Tipo de resultado:", type(resultado_2))
print("Tipo del primer elemento:", type(resultado_2[0]))
print("Resultado completo:", resultado_2)
print("Etiqueta:", resultado_2[0]["label"])
print("Confianza:", resultado_2[0]["score"])

Tipo de resultado: <class 'list'>
Tipo del primer elemento: <class 'dict'>
Resultado completo: [{'label': 'positive', 'score': 0.9853597283363342}]
Etiqueta: positive
Confianza: 0.9853597283363342

### Comparación de los valores de retorno

Los dos modelos ejecutados mediante `pipeline` devuelven una lista que contiene un diccionario por cada texto analizado. En ambos casos, `type()` permitió comprobar que el resultado es de tipo `list` y que el primer elemento es de tipo `dict`.

La etiqueta se obtiene mediante la clave `"label"` y el puntaje mediante la clave `"score"`. Por ejemplo, `resultado_2[0]["label"]` devuelve `"positive"` para la frase analizada.

El puntaje representa la confianza asignada por el modelo a su predicción, pero no garantiza que esta sea correcta. En nuestro caso, el Modelo 2 asignó un score de aproximadamente 0,9854 a la frase «La película fue excelente y me encantó.», clasificándola como positiva.