In [28]:
from transformers import pipeline

In [29]:
%pip install transformers

Requirement already satisfied: transformers in /usr/local/python/3.14.2/lib/python3.14/site-packages (5.18.0)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from transformers) (1.33.0)
Requirement already satisfied: numpy>=1.17 in /home/codespace/.local/lib/python3.14/site-packages (from transformers) (2.5.3)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.14/site-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /home/codespace/.local/lib/python3.14/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from transformers) (2026.9.29)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from transformers) (0.23.2)
Requirement already satisfied: typer in /home/codespace/.local/lib/python3.14/site-packages (from transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /home/codespace/.local/lib/python3.14/site-packages (from transformers) (4.70.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /home/codespace/.local/lib/python3.14/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /home/codespace/.local/lib/python3.14/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.0.12)
Requirement already satisfied: fsspec>=2023.5.0 in /home/codespace/.local/lib/python3.14/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2026.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /home/codespace/.local/lib/python3.14/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/codespace/.local/lib/python3.14/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/codespace/.local/lib/python3.14/site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.16.0)
Requirement already satisfied: anyio in /home/codespace/.local/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (4.15.1)
Requirement already satisfied: certifi in /home/codespace/.local/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /home/codespace/.local/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (1.0.9)
Requirement already satisfied: idna in /home/codespace/.local/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (3.19)
Requirement already satisfied: h11>=0.16 in /home/codespace/.local/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /home/codespace/.local/lib/python3.14/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/codespace/.local/lib/python3.14/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/codespace/.local/lib/python3.14/site-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/codespace/.local/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/codespace/.local/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /home/codespace/.local/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [30]:
modelo_1 = pipeline(
    "sentiment-analysis",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
)

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 2263.77it/s]

In [31]:
%pip install torch

Requirement already satisfied: torch in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.14.1)
Requirement already satisfied: filelock in /home/codespace/.local/lib/python3.14/site-packages (from torch) (4.0.12)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/codespace/.local/lib/python3.14/site-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools>=77.0.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from torch) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from torch) (3.7)
Requirement already satisfied: jinja2 in /home/codespace/.local/lib/python3.14/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /home/codespace/.local/lib/python3.14/site-packages (from torch) (2026.9.0)
Requirement already satisfied: cuda-toolkit==13.0.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from torch) (13.4.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.24.0.43 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from torch) (9.24.0.43)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from torch) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.30.7 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from torch) (2.30.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from torch) (3.4.5)
Requirement already satisfied: triton~=3.8.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from torch) (3.8.0)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.4.92)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from cuda-bindings<14,>=13.0.3->torch) (1.8.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.local/lib/python3.14/site-packages (from jinja2->torch) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [32]:
modelo_1("This movie was absolutely amazing!")

[{'label': 'POSITIVE', 'score': 0.9998781681060791}]

## Primera prueba del Modelo 1

Utilizamos el modelo `distilbert/distilbert-base-uncased-finetuned-sst-2-english`
mediante `pipeline` de Transformers.

La frase utilizada fue:

> "This movie was absolutely amazing!"

El modelo devuelve una etiqueta de sentimiento (`POSITIVE` o `NEGATIVE`)
junto con un valor de confianza (`score`).

In [33]:
frases = [
    "This movie was absolutely amazing!",
    "I hated every minute of this movie.",
    "La película fue excelente y me encantó.",
    "La película fue aburrida y demasiado larga.",
    "Yeah, great movie... I almost fell asleep.",
    "This movie was sick!",
    "Meh.",
    "The acting was good, but the story was terrible."
]

In [34]:
resultados_modelo_1 = modelo_1(frases)

resultados_modelo_1

[{'label': 'POSITIVE', 'score': 0.9998781681060791},
 {'label': 'NEGATIVE', 'score': 0.9996154308319092},
 {'label': 'POSITIVE', 'score': 0.9832308292388916},
 {'label': 'NEGATIVE', 'score': 0.9936158657073975},
 {'label': 'NEGATIVE', 'score': 0.9850236177444458},
 {'label': 'NEGATIVE', 'score': 0.9997525811195374},
 {'label': 'NEGATIVE', 'score': 0.5079557299613953},
 {'label': 'NEGATIVE', 'score': 0.9929336309432983}]

In [35]:
modelo_2 = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 18791.77it/s]
[transformers] Could not extract SentencePiece model from /home/codespace/.cache/huggingface/hub/models--cardiffnlp--twitter-xlm-roberta-base-sentiment/snapshots/f2f1202b1bdeb07342385c3f807f9c07cd8f5cf8/sentencepiece.bpe.model using sentencepiece library due to
SentencePieceExtractor requires the SentencePiece library but it was not found in your environment. Check out the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
. Falling back to TikToken extractor.

ValueError: Error parsing line b'\x0e' in /home/codespace/.cache/huggingface/hub/models--cardiffnlp--twitter-xlm-roberta-base-sentiment/snapshots/f2f1202b1bdeb07342385c3f807f9c07cd8f5cf8/sentencepiece.bpe.model

In [ ]:
%pip install tiktoken

Requirement already satisfied: tiktoken in /usr/local/python/3.14.2/lib/python3.14/site-packages (0.14.0)
Requirement already satisfied: regex in /usr/local/python/3.14.2/lib/python3.14/site-packages (from tiktoken) (2026.9.29)
Requirement already satisfied: requests in /home/codespace/.local/lib/python3.14/site-packages (from tiktoken) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.14/site-packages (from requests->tiktoken) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.14/site-packages (from requests->tiktoken) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /home/codespace/.local/lib/python3.14/site-packages (from requests->tiktoken) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/codespace/.local/lib/python3.14/site-packages (from requests->tiktoken) (2026.7.22)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
%pip install sentencepiece

Requirement already satisfied: sentencepiece in /usr/local/python/3.14.2/lib/python3.14/site-packages (0.2.2)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import sentencepiece

print(sentencepiece.__version__)

0.2.2

In [ ]:
from transformers import AutoTokenizer

tokenizer_2 = AutoTokenizer.from_pretrained(
    "cardiffnlp/twitter-xlm-roberta-base-sentiment",
    use_fast=False
)

[transformers] Could not extract SentencePiece model from /home/codespace/.cache/huggingface/hub/models--cardiffnlp--twitter-xlm-roberta-base-sentiment/snapshots/f2f1202b1bdeb07342385c3f807f9c07cd8f5cf8/sentencepiece.bpe.model using sentencepiece library due to
SentencePieceExtractor requires the SentencePiece library but it was not found in your environment. Check out the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
. Falling back to TikToken extractor.

ValueError: Error parsing line b'\x0e' in /home/codespace/.cache/huggingface/hub/models--cardiffnlp--twitter-xlm-roberta-base-sentiment/snapshots/f2f1202b1bdeb07342385c3f807f9c07cd8f5cf8/sentencepiece.bpe.model

In [ ]:
import transformers

print(transformers.__version__)

5.18.0

In [ ]:
pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment",
    tokenizer="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)



modelo_2 = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment",
    tokenizer="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 5013.11it/s]
[transformers] Could not extract SentencePiece model from /home/codespace/.cache/huggingface/hub/models--cardiffnlp--twitter-xlm-roberta-base-sentiment/snapshots/f2f1202b1bdeb07342385c3f807f9c07cd8f5cf8/sentencepiece.bpe.model using sentencepiece library due to
SentencePieceExtractor requires the SentencePiece library but it was not found in your environment. Check out the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
. Falling back to TikToken extractor.

ValueError: Error parsing line b'\x0e' in /home/codespace/.cache/huggingface/hub/models--cardiffnlp--twitter-xlm-roberta-base-sentiment/snapshots/f2f1202b1bdeb07342385c3f807f9c07cd8f5cf8/sentencepiece.bpe.model

In [ ]:
modelo_2 = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment-multilingual"
)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 3426.02it/s]

In [ ]:
resultados_modelo_2 = modelo_2(frases)

resultados_modelo_2

[{'label': 'positive', 'score': 0.9855308532714844},
 {'label': 'negative', 'score': 0.9136499166488647},
 {'label': 'positive', 'score': 0.9853597283363342},
 {'label': 'negative', 'score': 0.9610550999641418},
 {'label': 'positive', 'score': 0.9855705499649048},
 {'label': 'negative', 'score': 0.8911973237991333},
 {'label': 'neutral', 'score': 0.612568199634552},
 {'label': 'negative', 'score': 0.8974964022636414}]

In [ ]:
frases = [
    "This movie was absolutely amazing!",
    "I hated every minute of this movie.",
    "La película fue excelente y me encantó.",
    "La película fue aburrida y demasiado larga.",
    "Yeah, great movie... I almost fell asleep.",
    "This movie was sick!",
    "Meh.",
    "The acting was good, but the story was terrible."
]

In [37]:
import pandas as pd

esperados = [
    "positive",
    "negative",
    "positive",
    "negative",
    "negative",
    "positive",
    "negative"
]

tabla_comparacion = pd.DataFrame({
    "Frase": frases,
    "Esperado": esperados,
    "Modelo 1": [r["label"].lower() for r in resultados_modelo_1],
    "Score M1": [r["score"] for r in resultados_modelo_1],
    "Modelo 2": [r["label"].lower() for r in resultados_modelo_2],
    "Score M2": [r["score"] for r in resultados_modelo_2]
})

tabla_comparacion

ValueError: All arrays must be of the same length

In [42]:
print("Frases:", len(frases))
print("Esperados:", len(esperados))
print("Modelo 1:", len(resultados_modelo_1))
print("Modelo 2:", len(resultados_modelo_2))

Frases: 8
Esperados: 8
Modelo 1: 8
Modelo 2: 8

In [41]:
esperados = [
    "positive",
    "negative",
    "positive",
    "negative",
    "negative",
    "positive",
    "neutral",
    "negative"
]

In [43]:
print("Frases:", len(frases))
print("Esperados:", len(esperados))
print("Modelo 1:", len(resultados_modelo_1))
print("Modelo 2:", len(resultados_modelo_2))

Frases: 8
Esperados: 8
Modelo 1: 8
Modelo 2: 8

In [44]:
tabla_comparacion = pd.DataFrame({
    "Frase": frases,
    "Esperado": esperados,
    "Modelo 1": [r["label"].lower() for r in resultados_modelo_1],
    "Score M1": [r["score"] for r in resultados_modelo_1],
    "Modelo 2": [r["label"].lower() for r in resultados_modelo_2],
    "Score M2": [r["score"] for r in resultados_modelo_2]
})

tabla_comparacion

,Frase,Esperado,Modelo 1,Score M1,Modelo 2,Score M2
0,This movie was absolutely amazing!,positive,positive,0.999878,positive,0.985531
1,I hated every minute of this movie.,negative,negative,0.999615,negative,0.913650
2,La película fue excelente y me encantó.,positive,positive,0.983231,positive,0.985360
3,La película fue aburrida y demasiado larga.,negative,negative,0.993616,negative,0.961055
4,"Yeah, great movie... I almost fell asleep.",negative,negative,0.985024,positive,0.985571
5,This movie was sick!,positive,negative,0.999753,negative,0.891197
6,Meh.,neutral,negative,0.507956,neutral,0.612568
7,"The acting was good, but the story was terrible.",negative,negative,0.992934,negative,0.897496

In [45]:
tabla_comparacion["Acierto M1"] = (
    tabla_comparacion["Modelo 1"] == tabla_comparacion["Esperado"]
)

tabla_comparacion["Acierto M2"] = (
    tabla_comparacion["Modelo 2"] == tabla_comparacion["Esperado"]
)

tabla_comparacion

,Frase,Esperado,Modelo 1,Score M1,Modelo 2,Score M2,Acierto M1,Acierto M2
0,This movie was absolutely amazing!,positive,positive,0.999878,positive,0.985531,True,True
1,I hated every minute of this movie.,negative,negative,0.999615,negative,0.913650,True,True
2,La película fue excelente y me encantó.,positive,positive,0.983231,positive,0.985360,True,True
3,La película fue aburrida y demasiado larga.,negative,negative,0.993616,negative,0.961055,True,True
4,"Yeah, great movie... I almost fell asleep.",negative,negative,0.985024,positive,0.985571,True,False
5,This movie was sick!,positive,negative,0.999753,negative,0.891197,False,False
6,Meh.,neutral,negative,0.507956,neutral,0.612568,False,True
7,"The acting was good, but the story was terrible.",negative,negative,0.992934,negative,0.897496,True,True

In [46]:
print("Aciertos Modelo 1:", tabla_comparacion["Acierto M1"].sum(), "de", len(tabla_comparacion))
print("Aciertos Modelo 2:", tabla_comparacion["Acierto M2"].sum(), "de", len(tabla_comparacion))

Aciertos Modelo 1: 6 de 8
Aciertos Modelo 2: 6 de 8

In [47]:
tabla_comparacion[
    (tabla_comparacion["Acierto M1"] == False) |
    (tabla_comparacion["Acierto M2"] == False)
]

,Frase,Esperado,Modelo 1,Score M1,Modelo 2,Score M2,Acierto M1,Acierto M2
4,"Yeah, great movie... I almost fell asleep.",negative,negative,0.985024,positive,0.985571,True,False
5,This movie was sick!,positive,negative,0.999753,negative,0.891197,False,False
6,Meh.,neutral,negative,0.507956,neutral,0.612568,False,True